print("Hello! What is your name?")
name = input()
print("Hi! " + name + " Nice To meet you.")
nameLen = len(name)
print("Your name length is :- " )
print(nameLen)
print("What is your age?")
age = int(input())
print(name + " your age will be " + str(age + 1) + " after on year.")